#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub
{
  gosub list -app github.com/jeffpak/local-controller-plugin/cmd/...
  gosub list -app github.com/jeffpak/local-node-plugin/cmd/...

  # separate test and binary dependencies
  gosub list -test github.com/jeffpak/local-controller-plugin/...
  gosub list -test github.com/jeffpak/local-node-plugin/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync
